"""add new column for U user info table

Revision ID: 0451c25230c3
Revises: 73c642638533
Create Date: 2019-06-16 19:38:37.761872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0451c25230c3'
down_revision = '73c642638533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_user', sa.Column('shoulder', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_user', 'shoulder')
    # ### end Alembic commands ###
