"""change table exercicises

Revision ID: 20cfc832f8f6
Revises: 8a3e5f0f5eaa
Create Date: 2019-06-05 17:38:27.864173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20cfc832f8f6'
down_revision = '8a3e5f0f5eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('training_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercises', 'training', ['training_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'training_id')
    op.drop_column('exercises', 'day')
    op.drop_column('exercises', 'count')
    # ### end Alembic commands ###
