"""new userinfo table

Revision ID: 4a1e19b9bfd3
Revises: cba641b4ed68
Create Date: 2019-05-29 18:26:12.094818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1e19b9bfd3'
down_revision = 'cba641b4ed68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinfo',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.String(length=12), nullable=True),
    sa.Column('arms', sa.Integer(), nullable=True),
    sa.Column('chest', sa.Integer(), nullable=True),
    sa.Column('waist', sa.Integer(), nullable=True),
    sa.Column('femur', sa.Integer(), nullable=True),
    sa.Column('heartDiseases', sa.Integer(), nullable=True),
    sa.Column('date_of_change', sa.DateTime(), nullable=True),
    sa.Column('trainingList_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trainingList_id'], ['training_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userinfo')
    # ### end Alembic commands ###
