"""sports table

Revision ID: 4b91c22d9c22
Revises: bbe34bb061df
Create Date: 2019-05-28 19:18:58.107761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b91c22d9c22'
down_revision = 'bbe34bb061df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_sport', sa.String(length=256), nullable=True),
    sa.Column('info', sa.Text(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sport_info'), 'sport', ['info'], unique=False)
    op.create_index(op.f('ix_sport_name_sport'), 'sport', ['name_sport'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sport_name_sport'), table_name='sport')
    op.drop_index(op.f('ix_sport_info'), table_name='sport')
    op.drop_table('sport')
    # ### end Alembic commands ###
