"""exercises table

Revision ID: 72330e30a06e
Revises: 84977d65cda4
Create Date: 2019-05-28 21:01:30.837064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72330e30a06e'
down_revision = '84977d65cda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_exercises', sa.String(length=256), nullable=True),
    sa.Column('rules', sa.Text(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_name_exercises'), 'exercises', ['name_exercises'], unique=False)
    op.create_index(op.f('ix_exercises_rules'), 'exercises', ['rules'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_rules'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name_exercises'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
