"""change table user

Revision ID: 73c642638533
Revises: 34cda08dffd1
Create Date: 2019-06-06 22:18:43.557437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c642638533'
down_revision = '34cda08dffd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_training', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active_training')
    # ### end Alembic commands ###
