"""training list table

Revision ID: 84977d65cda4
Revises: bf158da7b620
Create Date: 2019-05-28 19:43:06.010484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84977d65cda4'
down_revision = 'bf158da7b620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_finish', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_list_date_start'), 'training_list', ['date_start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_list_date_start'), table_name='training_list')
    op.drop_table('training_list')
    # ### end Alembic commands ###
