"""upd userinfo table

Revision ID: 8a3e5f0f5eaa
Revises: 4a1e19b9bfd3
Create Date: 2019-05-29 19:39:15.532510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3e5f0f5eaa'
down_revision = '4a1e19b9bfd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('arms', sa.Integer(), nullable=True),
    sa.Column('chest', sa.Integer(), nullable=True),
    sa.Column('waist', sa.Integer(), nullable=True),
    sa.Column('femur', sa.Integer(), nullable=True),
    sa.Column('heartDiseases', sa.String(length=12), nullable=True),
    sa.Column('date_of_change', sa.DateTime(), nullable=True),
    sa.Column('training_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['training_list_id'], ['training_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('userinfo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinfo',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.INTEGER(), nullable=True),
    sa.Column('height', sa.VARCHAR(length=12), nullable=True),
    sa.Column('arms', sa.INTEGER(), nullable=True),
    sa.Column('chest', sa.INTEGER(), nullable=True),
    sa.Column('waist', sa.INTEGER(), nullable=True),
    sa.Column('femur', sa.INTEGER(), nullable=True),
    sa.Column('heartDiseases', sa.INTEGER(), nullable=True),
    sa.Column('date_of_change', sa.DATETIME(), nullable=True),
    sa.Column('trainingList_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['trainingList_id'], ['training_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('info_user')
    # ### end Alembic commands ###
