"""training table

Revision ID: bf158da7b620
Revises: 4b91c22d9c22
Create Date: 2019-05-28 19:22:56.529653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf158da7b620'
down_revision = '4b91c22d9c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_training', sa.String(length=256), nullable=True),
    sa.Column('tipe', sa.String(length=256), nullable=True),
    sa.Column('muscle_group', sa.String(length=256), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('count_day', sa.Integer(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_name_training'), 'training', ['name_training'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_name_training'), table_name='training')
    op.drop_table('training')
    # ### end Alembic commands ###
